Issue: 3482083 Remove sudo command from install script
Mellanox/ufm_sdk_3.0 pull request #114
Opened 2023-07-12 15:09 UTC by anasbadaha

2023-07-12 15:26 UTC, mike-dubman commented on plugins/SLURM-Integration/README.md
> +	   sudo ./install.sh
script should check if active user is root
```
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi
```

2023-07-12 15:30 UTC, mike-dubman commented on plugins/SLURM-Integration/install.sh
> +# Get the current PATH
just need to do
```export PATH=$PATH:/some/new/path1:/new/path2```

and let ```type``` search through PATH for a binary
lines 30-38, 43-72 are not needed

2023-07-12 15:33 UTC, mike-dubman commented on plugins/SLURM-Integration/install.sh
> +        echo "Failed to run (type -p pip3) command to get pip3 path, please make sure that pip3 is installed and configured appropriately, prior to running the UFM-Slurm integration."
all errors should be smth like
``` Error: unable to find file: $file in PATH=$PATH, please update PATH variable with correct location and rerun ```

2023-07-12 15:54 UTC, mike-dubman commented on plugins/SLURM-Integration/install.sh
> +        chmod 755 "$SLURM_DIR/$file"
yep
only exe files should be 755, text files should be 600

2023-07-12 15:58 UTC, anasbadaha commented on plugins/SLURM-Integration/install.sh
> +        chmod 755 "$SLURM_DIR/$file"
correct, you can see that all the files in the list in line 100 are exe files.

2023-07-13 06:46 UTC, kedeme requested changes

2023-07-13 06:46 UTC, kedeme commented on plugins/SLURM-Integration/README.md
> +	   sudo ./install.sh
or run the ./install.sh with root permissions

2023-07-13 06:46 UTC, kedeme commented on plugins/SLURM-Integration/install.sh
> +        echo "Error: unable to find python3 in PATH=$PATH, please update PATH variable with correct location and rerun"
with the valid path of Python3 and rerun

2023-07-13 06:46 UTC, kedeme commented on plugins/SLURM-Integration/install.sh
> +        echo "Error: unable to find pip3 in PATH=$PATH, please update PATH variable with correct location and rerun"
same as above with pip3

2023-07-13 06:46 UTC, kedeme commented on plugins/SLURM-Integration/install.sh
> +        echo "File $SLURM_DIR/$file_name is not writable or does not exist."
exit 2

2023-07-13 07:02 UTC, kedeme approved these changes

2023-07-13 07:03 UTC, merged

2023-07-13 07:04 UTC, mike-dubman commented on plugins/SLURM-Integration/install.sh
> +        echo "Error: unable to find python3 in PATH=$PATH, please update PATH variabe with the valid path of Python3 and rerun"
typo: variable

2023-07-13 07:13 UTC, mike-dubman commented on plugins/SLURM-Integration/install.sh
> +    if [ ! "$(id -u)" = "0" ]; then
```id``` is linux binary that not always installed, better to use bash/sh built-in env variables like ```EUID``` which is always be correct

2023-07-13 07:24 UTC, mike-dubman commented
@kedeme - not all comments addressed before merge

also - need to add CI (@lennybe ) - where installer is running in pristine container env (rhel7-8, ub for fail) and connect it to repo.
@lennybe - why it is not part of CI

2023-07-14 04:02 UTC, kedeme commented
@mike-dubman - we will fix the comments on a separate PR, I didn't want to delay the creating of the new SLURM integration build and testing the fixes by verification.

2023-07-14 14:10 UTC, mike-dubman commented
> @mike-dubman - we will fix the comments on a separate PR, I didn't want to delay the creating of the new SLURM integration build and testing the fixes by verification.

but w/o seeing green CI - you risk providing broken build to verification and wasting their time

should be clear gate - CI passed before passing to verification