enable test failed
Mellanox/ufm_sdk_3.0 pull request #121
Opened 2023-08-07 15:23 UTC by rondomnitz

2023-08-30 13:36 UTC, rondomnitz commented
bot:retest

2023-08-30 16:47 UTC, rondomnitz commented
bot:retest

2023-09-03 13:47 UTC, rondomnitz commented
bot:retest

2023-09-04 08:48 UTC, rondomnitz commented
bot:retest

2023-09-04 09:47 UTC, rondomnitz commented
bot:retest

2023-09-04 10:45 UTC, rondomnitz commented
bot:retest

2023-09-04 10:56 UTC, rondomnitz commented
bot:retest

2023-09-04 12:55 UTC, rondomnitz commented
bot:retest

2023-09-05 11:40 UTC, rondomnitz commented
bot:retest

2023-09-26 08:50 UTC, atolikin94 requested changes

2023-09-26 08:50 UTC, atolikin94 commented on plugins/UFM_NDT_Plugin/.ci/ci_matrix.yaml
> +      plugins/UFM_NDT_Plugin/.ci/draft.sh
please use more meaningful name

2023-09-26 08:50 UTC, atolikin94 commented on plugins/UFM_NDT_Plugin/.ci/ci_matrix.yaml
> +      plugins/UFM_NDT_Plugin/.ci/real_fabric.sh
as far as I can see, this script just stops UFM, please rename accordingly

2023-09-26 08:50 UTC, atolikin94 commented on plugins/UFM_NDT_Plugin/.ci/ci_matrix.yaml
>  pipeline_start:
please don't remove the build in pipeline_stop, these build artifacts could be useful for debugging

2023-09-26 09:38 UTC, rondomnitz commented
bot:retest

2023-09-26 11:22 UTC, rondomnitz commented
bot:retest

2023-09-26 12:16 UTC, rondomnitz commented
bot:retest

2023-09-26 13:18 UTC, rondomnitz commented
bot:retest

2023-09-26 14:11 UTC, rondomnitz commented
bot:retest

2023-09-26 14:41 UTC, rondomnitz commented
bot:retest

2023-09-27 08:45 UTC, rondomnitz commented
bot:retest

2023-09-27 09:28 UTC, rondomnitz commented
bot:retest

2023-09-27 10:23 UTC, rondomnitz commented
bot:retest

2023-09-27 11:11 UTC, merged