changed the plugin build path to /mswg/release/ufm/plugins*
Mellanox/ufm_sdk_3.0 pull request #165
Opened 2024-01-16 16:05 UTC by shahar-spormas

## What
update ci 

## Why ?
change the official path to be  `/mswg/release/ufm/plugins/*`

## How ?
changed it 

## Testing ?
locally

2024-01-17 13:58 UTC, lennybe requested changes

2024-01-17 14:10 UTC, shahar-spormas commented on .ci/matrix_job_release.yaml
> +      ls /auto/mswg/release/ufm/plugins/${Plugin_name}
its for the jenkins console

2024-01-17 14:11 UTC, shahar-spormas commented on .ci/Dockerfile
tmp fix, will try to put it in jenkins secrets now

2024-01-17 15:01 UTC, shahar-spormas commented on .ci/Dockerfile
changed it to mount

2024-01-17 15:14 UTC, lennybe requested changes

2024-01-17 15:14 UTC, lennybe commented on .ci/matrix_job_release.yaml
> +      ls /auto/mswg/release/ufm/plugins/${Plugin_name}
if ./docker_build.sh will fail, you will not know about it.

2024-01-17 15:25 UTC, shahar-spormas commented on .ci/matrix_job_release.yaml
> +      ls /auto/mswg/release/ufm/plugins/${Plugin_name}
NP, added an exit code checker

2024-01-18 08:21 UTC, shahar-spormas commented on .ci/matrix_job_release.yaml
> +      ls /auto/mswg/release/ufm/plugins/${Plugin_name}
now it exit with the build code as we talked about f2f

2024-01-18 09:11 UTC, lennybe commented on .ci/matrix_job_release.yaml
> +        exit 1
please print the reason for the failure before you exit.
you want to see and not guess the reason of the failure

2024-01-18 09:17 UTC, lennybe requested changes

2024-01-18 09:17 UTC, lennybe commented on .ci/matrix_job_release.yaml
> +        echo -e "A path and plugin with this version already exist."
please print the full path.
otherwize you will spend years by guessing what is existing:)

2024-01-18 11:47 UTC, lennybe approved these changes

2024-01-18 11:47 UTC, merged