Issue:3174324 pdr plugin support
Mellanox/ufm_sdk_3.0 pull request #50
Opened 2023-01-04 07:53 UTC by drorlevy

2023-01-29 07:38 UTC, drorlevy commented
bot:retest

2023-03-22 13:33 UTC, kedeme requested changes

2023-03-22 13:33 UTC, kedeme commented on plugins/pdr_deterministic_plugin/ufm_sim_web_service/ufm_communication_mgr.py
> +        if response.status_code == 200:
use HTTP_OK constant

2023-03-22 15:20 UTC, drorlevy commented on plugins/pdr_deterministic_plugin/ufm_sim_web_service/isolation_mgr.py
> +    def get_port_metadata(self, port_name):
but it's also the width and hw_technology

2023-03-22 15:24 UTC, drorlevy commented on plugins/pdr_deterministic_plugin/build/config/fec_mode_lookup.json
> +{
there isn't such a location. maybe in the arch documents of the firmware. this code is taken from the telemetry team

2023-03-22 15:26 UTC, drorlevy commented on plugins/pdr_deterministic_plugin/build/config/supervisord.conf
> +command=python3 /opt/ufm/ufm_plugin_pdr_deterministic/ufm_sim_web_service/isolation_algo.py
it is to keep with the convention of other plugins

2023-03-22 15:27 UTC, drorlevy commented on plugins/pdr_deterministic_plugin/build/docker_build.sh
> +IMAGE_NAME=ufm-plugin-pdr_deterministic
packet drop rate? i kept it as the name of the feature but up to you

2023-03-23 13:27 UTC, kedeme approved these changes

2023-03-23 13:27 UTC, merged